version: "3"
services:
  mysql:
    image: mysql
    command: --server-id=1
      --log-bin=mysql-bin
      --binlog-format=ROW
      --sync-binlog=1
      --log-slave-updates=ON
      --gtid-mode=ON
      --enforce-gtid-consistency=ON
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --binlog-rows-query-log-events=1
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "33306:3306"

  memcached:
    image: memcached
    ports:
      - "11211:11211"
